//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManage.ProjectBasicinfo {
    
    
    public partial class ProjectBasicInfoDetail {
        
        /// <summary>
        /// ProjectClass1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ProjectManage.Common.UserControls.ProjectClass ProjectClass1;
        
        /// <summary>
        /// ProjectNature1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ProjectManage.Common.UserControls.ProjectNature ProjectNature1;
        
        /// <summary>
        /// Customer1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ProjectManage.Common.UserControls.Customer Customer1;
        
        /// <summary>
        /// Users1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ProjectManage.Common.UserControls.Users Users1;
        
        /// <summary>
        /// ChooseUsersControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ProjectManage.Common.ChooseUsersControl ChooseUsersControl1;
    }
}
